project:
  type: website
  output-dir: _site
  resources:
    - "pr-*/"

website:
  title: "PR Preview"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
